# Generated by Django 4.0 on 2021-12-21 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_order_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='notes',
            new_name='note',
        ),
    ]
